version: "3.1"
services:
  sqlite-web:
    image: "coleifer/sqlite-web"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=plates.db
  grafana:
    image: "grafana/grafana-enterprise"
    # user: $USER
    ports:
      - "3000:3000"
    volumes:
      - ./data:/var/lib/grafana
    environment:
      - GF_PATHS_CONFIG=/var/lib/grafana/grafana/grafana.ini
